#! /bin/zsh

PORT=1180
HOST=127.0.0.1

if [ -n "$2" ]; then
  PORT="$2"
fi
if [ -n "$3" ]; then
  HOST="$3"
fi

case "$1" in
  on)
    git config --global http.proxy http://$HOST:$PORT
    printf """
    Current proxy by
    `git config --get http.proxy`
    \n"""
    ;;
  off)
    git config --global --unset http.proxy
    ;;
  *)
    echo "Current proxy by"
    git config --get http.proxy
    printf """
    You can use \"git proxy on | off\" to change proxy setting

    git proxy on
    git proxy on 9090
    git proxy on 9090 10.0.0.100
    \n"""
    ;;
esac



