services:
  registry:
    image: 172.16.201.11:5000/registry:3
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"