winpos 885 412
set lines=30
set columns=120
set nocompatible
set nobackup
set noswapfile
set history=2048
set autochdir
set whichwrap=b,s,<,>,[,]
set nobomb
set nowrap
set backspace=indent,eol,start whichwrap+=<,>,[,]
set fileencodings=utf-8,gbk2312,gbk,gb18030,cp936
set guifont=Cascadia_Code:h9:i:cANSI:qDRAFT
set encoding=utf-8
set langmenu=zh_CN
let $LANG = 'en_US.UTF-8'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
set cursorline cursorcolumn
set hlsearch
set number
set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=b
set autoindent
set smartindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set foldmethod=indent
set wildmenu
# 参考
# https://vi.stackexchange.com/questions/23066/change-cursorline-style
# https://stackoverflow.com/questions/8640276/how-do-i-change-my-vim-highlight-line-to-not-be-an-underline
#
# hi CursorColumn ctermbg=242
# hi CursorLine cterm=NONE ctermbg=242
syntax on
let mapleader="\\"
noremap <Leader>y "*y
nnoremap <Leader>p "*p
vnoremap <Leader>p "*p
nnoremap <Leader>x :set paste<CR>
nnoremap <Leader>X :set nopaste<CR>
noremap <Leader>r :bro ol
noremap <Leader>ss :source ~/.vimrc
noremap <Leader>se :e ~/.vimrc
nmap [n :set nu rnu<CR>
nmap ]n :set nonu nornu<CR>
nmap [w :set wrap<CR>
nmap ]w :set nowrap<CR>
