services:
  redis:
    image: 127.0.0.1:5000/redis:7-alpine
    container_name: redis
    restart: unless-stopped    
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-net
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  redis:
    driver: bridge
