#!/bin/bash
# 合并方向 $current$ -> master -> staging

CURR_BR=$(git symbolic-ref --short HEAD)
TARGET_BRANCH="$1"
MASTER_BR="master"
STAGING_BR="staging"

if [ "$TARGET_BRANCH" == "" ]; then
  TARGET_BRANCH="$CURR_BR"
  printf "\nNo branch specified, use current branch ($TARGET_BRANCH)\n"
fi

if [ "$TARGET_BRANCH" == "$MASTER_BR" ]; then
  echo "Target can not same with '$MASTER_BR'"
  exit 2
fi

if [ "$TARGET_BRANCH" == "$STAGING_BR" ]; then
  echo "Target can not same with '$STAGING_BR'"
  exit 2
fi

printf "\nBefore merging $TARGET_BRANCH\n====\n\n"

git merging $TARGET_BRANCH &&
  printf "\nAfter merge $TARGET_BRANCH\n====\n\n" &&
  git merged &&
  printf "\nMerging master to staging\n====\n"
  git staging
