#!/bin/bash

CURR_BR=$(git symbolic-ref --short HEAD)
TAG_PREF=`date +%Y.%-m`

git checkout master
git pull -r
git tag -l | grep "$TAG_PREF"
printf "\nWhat is the Tag: "
read tag
echo ""
git tag -a "$tag"
git pt
git co $CURR_BR
