services:
  portainer:
    image: 127.0.0.1:5000/portainer/portainer-ce:2.30.1-alpine
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"