set smarttab
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

syn on
set guifont=Fira_Code:h10
set encoding=utf-8   
set rop=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1
set nowrap
set nu
set guioptions-=m
set guioptions-=T

nmap <C-v> "+gp
imap <C-v> <Esc>"+gpa
vmap <C-c> "+y
nmap <C-a> ggvG$

set nocompatible              " be iMproved, required
set backspace=indent,eol,start
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/vimfiles/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'godlygeek/tabular'
Plugin 'HerringtonDarkholme/yats.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'pangloss/vim-javascript'
Plugin 'mattn/emmet-vim'
Plugin 'drmingdrmer/xptemplate'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'plasticboy/vim-markdown'
Plugin 'chr4/nginx.vim'
Plugin 'valloric/youcompleteme'
Plugin 'Chiel92/vim-autoformat'
Plugin 'wincent/command-t'

" Add plugins here

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Set airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set laststatus=2
